import { PERMISSIONS, ROLES, type Permission, type Role } from "@/constants/app";

/* Role → permissions matrix. Backend remains the source of truth; this mirrors it for UI gating. */

const ALL: Permission[] = Object.values(PERMISSIONS);

const MANAGER_PERMS: Permission[] = [
  PERMISSIONS.DASHBOARD_READ,
  PERMISSIONS.CUSTOMERS_READ,
  PERMISSIONS.LEADS_READ,
  PERMISSIONS.OPPORTUNITIES_READ,
  PERMISSIONS.SALES_READ,
  PERMISSIONS.PURCHASES_READ,
  PERMISSIONS.PRODUCTS_READ,
  PERMISSIONS.INVENTORY_READ,
  PERMISSIONS.ACCOUNTING_READ,
  PERMISSIONS.EXPENSES_READ,
  PERMISSIONS.EMPLOYEES_READ,
  PERMISSIONS.ATTENDANCE_READ,
  PERMISSIONS.LEAVES_READ,
  PERMISSIONS.LEAVES_APPROVE,
  PERMISSIONS.PROJECTS_READ,
  PERMISSIONS.TASKS_READ,
  PERMISSIONS.ASSETS_READ,
  PERMISSIONS.DOCUMENTS_READ,
  PERMISSIONS.REPORTS_READ,
  PERMISSIONS.REPORTS_EXPORT,
  PERMISSIONS.SETTINGS_READ,
];

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [ROLES.SUPER_ADMIN]: ALL,
  [ROLES.ADMINISTRATOR]: ALL.filter((p) => p !== PERMISSIONS.ROLES_MANAGE),
  [ROLES.MANAGER]: [...MANAGER_PERMS, PERMISSIONS.SALES_APPROVE, PERMISSIONS.PURCHASES_APPROVE, PERMISSIONS.EXPENSES_APPROVE, PERMISSIONS.ACCOUNTING_APPROVE],
  [ROLES.ACCOUNTANT]: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.CUSTOMERS_READ,
    PERMISSIONS.SALES_READ,
    PERMISSIONS.PURCHASES_READ,
    PERMISSIONS.ACCOUNTING_READ,
    PERMISSIONS.ACCOUNTING_CREATE,
    PERMISSIONS.ACCOUNTING_UPDATE,
    PERMISSIONS.EXPENSES_READ,
    PERMISSIONS.EXPENSES_CREATE,
    PERMISSIONS.DOCUMENTS_READ,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.SETTINGS_READ,
  ],
  [ROLES.HR_MANAGER]: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.EMPLOYEES_READ,
    PERMISSIONS.EMPLOYEES_CREATE,
    PERMISSIONS.EMPLOYEES_UPDATE,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_MANAGE,
    PERMISSIONS.LEAVES_READ,
    PERMISSIONS.LEAVES_APPROVE,
    PERMISSIONS.PAYROLL_READ,
    PERMISSIONS.PAYROLL_MANAGE,
    PERMISSIONS.DOCUMENTS_READ,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.SETTINGS_READ,
  ],
  [ROLES.SALES_MANAGER]: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.CUSTOMERS_READ,
    PERMISSIONS.CUSTOMERS_CREATE,
    PERMISSIONS.CUSTOMERS_UPDATE,
    PERMISSIONS.LEADS_READ,
    PERMISSIONS.LEADS_CREATE,
    PERMISSIONS.LEADS_UPDATE,
    PERMISSIONS.OPPORTUNITIES_READ,
    PERMISSIONS.OPPORTUNITIES_CREATE,
    PERMISSIONS.OPPORTUNITIES_UPDATE,
    PERMISSIONS.SALES_READ,
    PERMISSIONS.SALES_CREATE,
    PERMISSIONS.SALES_UPDATE,
    PERMISSIONS.SALES_APPROVE,
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.DOCUMENTS_READ,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.SETTINGS_READ,
  ],
  [ROLES.SALES_EMPLOYEE]: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.CUSTOMERS_READ,
    PERMISSIONS.CUSTOMERS_CREATE,
    PERMISSIONS.CUSTOMERS_UPDATE,
    PERMISSIONS.LEADS_READ,
    PERMISSIONS.LEADS_CREATE,
    PERMISSIONS.LEADS_UPDATE,
    PERMISSIONS.OPPORTUNITIES_READ,
    PERMISSIONS.OPPORTUNITIES_CREATE,
    PERMISSIONS.SALES_READ,
    PERMISSIONS.SALES_CREATE,
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.DOCUMENTS_READ,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.SETTINGS_READ,
  ],
  [ROLES.PURCHASE_MANAGER]: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.PURCHASES_READ,
    PERMISSIONS.PURCHASES_CREATE,
    PERMISSIONS.PURCHASES_UPDATE,
    PERMISSIONS.PURCHASES_APPROVE,
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.DOCUMENTS_READ,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.SETTINGS_READ,
  ],
  [ROLES.INVENTORY_MANAGER]: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.PRODUCTS_CREATE,
    PERMISSIONS.PRODUCTS_UPDATE,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.INVENTORY_TRANSFER,
    PERMISSIONS.PURCHASES_READ,
    PERMISSIONS.DOCUMENTS_READ,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.SETTINGS_READ,
  ],
  [ROLES.EMPLOYEE]: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.LEAVES_READ,
    PERMISSIONS.LEAVES_CREATE,
    PERMISSIONS.TASKS_READ,
    PERMISSIONS.TASKS_UPDATE,
    PERMISSIONS.PROJECTS_READ,
    PERMISSIONS.DOCUMENTS_READ,
    PERMISSIONS.SETTINGS_READ,
  ],
  [ROLES.VIEWER]: [PERMISSIONS.DASHBOARD_READ, PERMISSIONS.REPORTS_READ, PERMISSIONS.SETTINGS_READ],
};

export function getPermissionsForRole(role: string): Permission[] {
  return (ROLE_PERMISSIONS[role as Role] ?? ROLE_PERMISSIONS[ROLES.VIEWER]).slice();
}

export function hasPermission(userPermissions: string[] | undefined, permission: Permission | string): boolean {
  if (!userPermissions) return false;
  return userPermissions.includes(permission);
}

export function hasAnyPermission(userPermissions: string[] | undefined, permissions: (Permission | string)[]): boolean {
  if (!userPermissions) return false;
  return permissions.some((p) => userPermissions.includes(p));
}

export function hasAllPermissions(userPermissions: string[] | undefined, permissions: (Permission | string)[]): boolean {
  if (!userPermissions) return false;
  return permissions.every((p) => userPermissions.includes(p));
}

export function hasRole(userRole: string | undefined, roles: Role | Role[] | string | string[]): boolean {
  if (!userRole) return false;
  const list = Array.isArray(roles) ? roles : [roles];
  return list.includes(userRole);
}

export function canAccessModule(userPermissions: string[] | undefined, modulePrefix: string): boolean {
  if (!userPermissions) return false;
  return userPermissions.some((p) => p === `${modulePrefix}.read` || p.startsWith(`${modulePrefix}.`));
}
