/* Centralized application constants — no magic strings elsewhere. */

export const APP_CONFIG = {
  name: "Nexora ERP",
  shortName: "Nexora",
  version: "2.4.0",
  defaultCurrency: "USD",
  defaultLocale: "en-US",
  defaultTimezone: "UTC",
  company: {
    name: "Nexora Industries Inc.",
    email: "finance@nexora.example",
    phone: "+1 (415) 555-0132",
    taxId: "US-84-2091741",
    address: "548 Market Street, San Francisco, CA 94104",
  },
} as const;

export const ROUTES = {
  ROOT: "/",
  LOGIN: "/login",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  VERIFY_2FA: "/verify-2fa",
  DASHBOARD: "/dashboard",
  CRM: {
    CUSTOMERS: "/crm/customers",
    CUSTOMER_DETAILS: "/crm/customers/:id",
    LEADS: "/crm/leads",
    OPPORTUNITIES: "/crm/opportunities",
    CONTACTS: "/crm/contacts",
  },
  SALES: {
    QUOTATIONS: "/sales/quotations",
    ORDERS: "/sales/orders",
    DELIVERIES: "/sales/deliveries",
    INVOICES: "/sales/invoices",
    INVOICE_DETAILS: "/sales/invoices/:id",
    CREDIT_NOTES: "/sales/credit-notes",
    PAYMENTS: "/sales/payments",
    RETURNS: "/sales/returns",
  },
  PURCHASES: {
    SUPPLIERS: "/purchases/suppliers",
    SUPPLIER_DETAILS: "/purchases/suppliers/:id",
    REQUESTS: "/purchases/requests",
    QUOTATIONS: "/purchases/quotations",
    ORDERS: "/purchases/orders",
    RECEIPTS: "/purchases/receipts",
    INVOICES: "/purchases/invoices",
    PAYMENTS: "/purchases/payments",
    RETURNS: "/purchases/returns",
  },
  INVENTORY: {
    PRODUCTS: "/inventory/products",
    PRODUCT_DETAILS: "/inventory/products/:id",
    CATEGORIES: "/inventory/categories",
    WAREHOUSES: "/inventory/warehouses",
    MOVEMENTS: "/inventory/movements",
    TRANSFERS: "/inventory/transfers",
    ADJUSTMENTS: "/inventory/adjustments",
    VALUATION: "/inventory/valuation",
  },
  ACCOUNTING: {
    OVERVIEW: "/accounting",
    CHART_OF_ACCOUNTS: "/accounting/chart-of-accounts",
    JOURNAL: "/accounting/journal",
    LEDGER: "/accounting/ledger",
    RECEIVABLES: "/accounting/receivables",
    PAYABLES: "/accounting/payables",
    EXPENSES: "/accounting/expenses",
    TAXES: "/accounting/taxes",
    PROFIT_LOSS: "/accounting/profit-loss",
    BALANCE_SHEET: "/accounting/balance-sheet",
    CASH_FLOW: "/accounting/cash-flow",
  },
  HR: {
    EMPLOYEES: "/hr/employees",
    EMPLOYEE_DETAILS: "/hr/employees/:id",
    DEPARTMENTS: "/hr/departments",
    ATTENDANCE: "/hr/attendance",
    LEAVES: "/hr/leaves",
    PAYROLL: "/hr/payroll",
    EVALUATIONS: "/hr/evaluations",
  },
  PROJECTS: {
    LIST: "/projects",
    DETAILS: "/projects/:id",
    TASKS: "/projects/tasks",
    MILESTONES: "/projects/milestones",
    TIME_TRACKING: "/projects/time-tracking",
  },
  ASSETS: {
    LIST: "/assets",
    DETAILS: "/assets/:id",
    MAINTENANCE: "/assets/maintenance",
  },
  DOCUMENTS: "/documents",
  REPORTS: "/reports",
  NOTIFICATIONS: "/notifications",
  APPROVALS: "/approvals",
  AUDIT_LOGS: "/audit-logs",
  SETTINGS: {
    ROOT: "/settings",
    COMPANY: "/settings/company",
    PROFILE: "/settings/profile",
    USERS: "/settings/users",
    ROLES: "/settings/roles",
    ERP: "/settings/erp",
    SECURITY: "/settings/security",
    NOTIFICATION_PREFS: "/settings/notifications",
  },
  FORBIDDEN: "/403",
  NOT_FOUND: "/404",
  SERVER_ERROR: "/500",
} as const;

export const PERMISSIONS = {
  DASHBOARD_READ: "dashboard.read",
  CUSTOMERS_READ: "customers.read",
  CUSTOMERS_CREATE: "customers.create",
  CUSTOMERS_UPDATE: "customers.update",
  CUSTOMERS_DELETE: "customers.delete",
  LEADS_READ: "leads.read",
  LEADS_CREATE: "leads.create",
  LEADS_UPDATE: "leads.update",
  LEADS_DELETE: "leads.delete",
  OPPORTUNITIES_READ: "opportunities.read",
  OPPORTUNITIES_CREATE: "opportunities.create",
  OPPORTUNITIES_UPDATE: "opportunities.update",
  OPPORTUNITIES_DELETE: "opportunities.delete",
  SALES_READ: "sales.read",
  SALES_CREATE: "sales.create",
  SALES_UPDATE: "sales.update",
  SALES_DELETE: "sales.delete",
  SALES_APPROVE: "sales.approve",
  PURCHASES_READ: "purchases.read",
  PURCHASES_CREATE: "purchases.create",
  PURCHASES_UPDATE: "purchases.update",
  PURCHASES_DELETE: "purchases.delete",
  PURCHASES_APPROVE: "purchases.approve",
  PRODUCTS_READ: "products.read",
  PRODUCTS_CREATE: "products.create",
  PRODUCTS_UPDATE: "products.update",
  PRODUCTS_DELETE: "products.delete",
  INVENTORY_READ: "inventory.read",
  INVENTORY_ADJUST: "inventory.adjust",
  INVENTORY_TRANSFER: "inventory.transfer",
  ACCOUNTING_READ: "accounting.read",
  ACCOUNTING_CREATE: "accounting.create",
  ACCOUNTING_UPDATE: "accounting.update",
  ACCOUNTING_APPROVE: "accounting.approve",
  EXPENSES_READ: "expenses.read",
  EXPENSES_CREATE: "expenses.create",
  EXPENSES_APPROVE: "expenses.approve",
  EMPLOYEES_READ: "employees.read",
  EMPLOYEES_CREATE: "employees.create",
  EMPLOYEES_UPDATE: "employees.update",
  EMPLOYEES_DELETE: "employees.delete",
  ATTENDANCE_READ: "attendance.read",
  ATTENDANCE_MANAGE: "attendance.manage",
  LEAVES_READ: "leaves.read",
  LEAVES_CREATE: "leaves.create",
  LEAVES_APPROVE: "leaves.approve",
  PAYROLL_READ: "payroll.read",
  PAYROLL_MANAGE: "payroll.manage",
  PROJECTS_READ: "projects.read",
  PROJECTS_CREATE: "projects.create",
  PROJECTS_UPDATE: "projects.update",
  PROJECTS_DELETE: "projects.delete",
  TASKS_READ: "tasks.read",
  TASKS_CREATE: "tasks.create",
  TASKS_UPDATE: "tasks.update",
  TASKS_DELETE: "tasks.delete",
  ASSETS_READ: "assets.read",
  ASSETS_CREATE: "assets.create",
  ASSETS_UPDATE: "assets.update",
  ASSETS_DELETE: "assets.delete",
  DOCUMENTS_READ: "documents.read",
  DOCUMENTS_CREATE: "documents.create",
  DOCUMENTS_UPDATE: "documents.update",
  DOCUMENTS_DELETE: "documents.delete",
  REPORTS_READ: "reports.read",
  REPORTS_EXPORT: "reports.export",
  SETTINGS_READ: "settings.read",
  SETTINGS_UPDATE: "settings.update",
  USERS_MANAGE: "users.manage",
  ROLES_MANAGE: "roles.manage",
  AUDIT_READ: "audit.read",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLES = {
  SUPER_ADMIN: "super_admin",
  ADMINISTRATOR: "administrator",
  MANAGER: "manager",
  ACCOUNTANT: "accountant",
  HR_MANAGER: "hr_manager",
  SALES_MANAGER: "sales_manager",
  SALES_EMPLOYEE: "sales_employee",
  PURCHASE_MANAGER: "purchase_manager",
  INVENTORY_MANAGER: "inventory_manager",
  EMPLOYEE: "employee",
  VIEWER: "viewer",
} as const;

export type Role = (typeof ROLES)[keyof typeof ROLES];

export const ROLE_LABELS: Record<Role, string> = {
  super_admin: "Super Admin",
  administrator: "Administrator",
  manager: "Manager",
  accountant: "Accountant",
  hr_manager: "HR Manager",
  sales_manager: "Sales Manager",
  sales_employee: "Sales Employee",
  purchase_manager: "Purchase Manager",
  inventory_manager: "Inventory Manager",
  employee: "Employee",
  viewer: "Viewer",
};

export const ORDER_STATUS = {
  DRAFT: "draft",
  PENDING_APPROVAL: "pending_approval",
  APPROVED: "approved",
  CONFIRMED: "confirmed",
  IN_PROGRESS: "in_progress",
  PARTIALLY_FULFILLED: "partially_fulfilled",
  FULFILLED: "fulfilled",
  DELIVERED: "delivered",
  CANCELLED: "cancelled",
  REJECTED: "rejected",
} as const;

export const QUOTATION_STATUS = {
  DRAFT: "draft",
  SENT: "sent",
  ACCEPTED: "accepted",
  REJECTED: "rejected",
  EXPIRED: "expired",
  CONVERTED: "converted",
  CANCELLED: "cancelled",
} as const;

export const INVOICE_STATUS = {
  DRAFT: "draft",
  SENT: "sent",
  VIEWED: "viewed",
  PARTIALLY_PAID: "partially_paid",
  PAID: "paid",
  OVERDUE: "overdue",
  CANCELLED: "cancelled",
  REFUNDED: "refunded",
} as const;

export const PAYMENT_STATUS = {
  PENDING: "pending",
  COMPLETED: "completed",
  FAILED: "failed",
  REFUNDED: "refunded",
  PARTIALLY_REFUNDED: "partially_refunded",
  CANCELLED: "cancelled",
} as const;

export const STOCK_STATUS = {
  IN_STOCK: "in_stock",
  LOW_STOCK: "low_stock",
  OUT_OF_STOCK: "out_of_stock",
  ON_ORDER: "on_order",
  DISCONTINUED: "discontinued",
} as const;

export const TASK_STATUS = {
  TODO: "todo",
  IN_PROGRESS: "in_progress",
  REVIEW: "review",
  COMPLETED: "completed",
  BLOCKED: "blocked",
} as const;

export const PRIORITY = {
  LOW: "low",
  MEDIUM: "medium",
  HIGH: "high",
  URGENT: "urgent",
} as const;

export const EMPLOYEE_STATUS = {
  ACTIVE: "active",
  ON_LEAVE: "on_leave",
  PROBATION: "probation",
  TERMINATED: "terminated",
  RESIGNED: "resigned",
} as const;

export const LEAVE_STATUS = {
  PENDING: "pending",
  APPROVED: "approved",
  REJECTED: "rejected",
  CANCELLED: "cancelled",
} as const;

export const APPROVAL_STATUS = {
  DRAFT: "draft",
  PENDING: "pending",
  APPROVED: "approved",
  REJECTED: "rejected",
  CHANGES_REQUESTED: "changes_requested",
} as const;

export const LEAD_STATUS = {
  NEW: "new",
  CONTACTED: "contacted",
  QUALIFIED: "qualified",
  PROPOSAL: "proposal",
  NEGOTIATION: "negotiation",
  WON: "won",
  LOST: "lost",
} as const;

export const OPPORTUNITY_STAGE = {
  DISCOVERY: "discovery",
  QUALIFICATION: "qualification",
  PROPOSAL: "proposal",
  NEGOTIATION: "negotiation",
  CLOSED_WON: "closed_won",
  CLOSED_LOST: "closed_lost",
} as const;

export const PROJECT_STATUS = {
  PLANNING: "planning",
  ACTIVE: "active",
  ON_HOLD: "on_hold",
  COMPLETED: "completed",
  CANCELLED: "cancelled",
} as const;

export const ASSET_STATUS = {
  AVAILABLE: "available",
  ASSIGNED: "assigned",
  IN_MAINTENANCE: "in_maintenance",
  RETIRED: "retired",
  DISPOSED: "disposed",
} as const;

export const CURRENCIES = [
  { code: "USD", symbol: "$", name: "US Dollar" },
  { code: "EUR", symbol: "€", name: "Euro" },
  { code: "GBP", symbol: "£", name: "British Pound" },
  { code: "AED", symbol: "د.إ", name: "UAE Dirham" },
  { code: "SAR", symbol: "﷼", name: "Saudi Riyal" },
] as const;

export const LANGUAGES = [
  { code: "en", label: "English", dir: "ltr" },
  { code: "fr", label: "Français", dir: "ltr" },
  { code: "ar", label: "العربية", dir: "rtl" },
] as const;

export const DATE_FORMATS = {
  DATE: "MMM d, yyyy",
  DATE_SHORT: "MM/dd/yyyy",
  DATETIME: "MMM d, yyyy h:mm a",
  TIME: "h:mm a",
  MONTH_YEAR: "MMMM yyyy",
  ISO: "yyyy-MM-dd",
} as const;

export const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_PAGE_SIZE: 10,
  PAGE_SIZE_OPTIONS: [10, 20, 50, 100],
} as const;

export const QUERY_KEYS = {
  dashboard: "dashboard",
  customers: "customers",
  customer: "customer",
  leads: "leads",
  opportunities: "opportunities",
  contacts: "contacts",
  quotations: "quotations",
  salesOrders: "sales-orders",
  deliveries: "deliveries",
  invoices: "invoices",
  invoice: "invoice",
  creditNotes: "credit-notes",
  payments: "payments",
  salesReturns: "sales-returns",
  suppliers: "suppliers",
  supplier: "supplier",
  purchaseRequests: "purchase-requests",
  purchaseQuotations: "purchase-quotations",
  purchaseOrders: "purchase-orders",
  goodsReceipts: "goods-receipts",
  supplierInvoices: "supplier-invoices",
  supplierPayments: "supplier-payments",
  purchaseReturns: "purchase-returns",
  products: "products",
  product: "product",
  categories: "categories",
  warehouses: "warehouses",
  movements: "movements",
  transfers: "transfers",
  adjustments: "adjustments",
  accounts: "accounts",
  journal: "journal",
  ledger: "ledger",
  receivables: "receivables",
  payables: "payables",
  expenses: "expenses",
  taxes: "taxes",
  employees: "employees",
  employee: "employee",
  departments: "departments",
  attendance: "attendance",
  leaves: "leaves",
  payroll: "payroll",
  projects: "projects",
  project: "project",
  tasks: "tasks",
  milestones: "milestones",
  timeEntries: "time-entries",
  assets: "assets",
  asset: "asset",
  documents: "documents",
  reports: "reports",
  notifications: "notifications",
  approvals: "approvals",
  auditLogs: "audit-logs",
  users: "users",
  roles: "roles",
} as const;

export const FILE_TYPES = {
  DOCUMENT: ["pdf", "doc", "docx", "txt", "rtf"],
  SPREADSHEET: ["xls", "xlsx", "csv"],
  IMAGE: ["jpg", "jpeg", "png", "gif", "webp", "svg"],
  ARCHIVE: ["zip", "rar", "7z"],
  ALL: ["pdf", "doc", "docx", "xls", "xlsx", "csv", "jpg", "jpeg", "png", "txt", "zip"],
} as const;

export const MAX_FILE_SIZE = 10 * 1024 * 1024; // 10MB

export const STORAGE_KEYS = {
  AUTH_TOKEN: "nexora.auth.token",
  REFRESH_TOKEN: "nexora.auth.refresh",
  USER: "nexora.auth.user",
  THEME: "nexora.ui.theme",
  SIDEBAR: "nexora.ui.sidebar",
  LOCALE: "nexora.ui.locale",
  CURRENCY: "nexora.ui.currency",
} as const;

export const STATUS_COLORS: Record<string, "default" | "success" | "warning" | "danger" | "info" | "secondary"> = {
  draft: "secondary",
  sent: "info",
  viewed: "info",
  pending: "warning",
  pending_approval: "warning",
  new: "info",
  active: "success",
  approved: "success",
  accepted: "success",
  confirmed: "success",
  completed: "success",
  paid: "success",
  delivered: "success",
  fulfilled: "success",
  converted: "success",
  won: "success",
  qualified: "success",
  closed_won: "success",
  available: "success",
  in_stock: "success",
  partially_paid: "warning",
  partially_fulfilled: "warning",
  partially_refunded: "warning",
  in_progress: "info",
  review: "warning",
  contacted: "info",
  proposal: "info",
  negotiation: "warning",
  discovery: "info",
  qualification: "info",
  on_order: "info",
  on_leave: "warning",
  probation: "warning",
  on_hold: "warning",
  low_stock: "warning",
  overdue: "danger",
  failed: "danger",
  cancelled: "danger",
  rejected: "danger",
  lost: "danger",
  closed_lost: "danger",
  blocked: "danger",
  terminated: "danger",
  resigned: "danger",
  out_of_stock: "danger",
  expired: "danger",
  refunded: "secondary",
  retired: "secondary",
  disposed: "secondary",
  discontinued: "secondary",
  assigned: "info",
  in_maintenance: "warning",
  todo: "secondary",
  planning: "secondary",
  changes_requested: "warning",
};
